import numpy as np
import matplotlib.pyplot as plt
import math

# --- 1. KONFIGURACE "ZDROJOVÉHO KÓDU" VESMÍRU ---
PI = np.pi
ALPHA_INV = 137.035999
ALPHA = 1.0 / ALPHA_INV
N = np.log(4 * PI)

# Převodní jednotky (pro vizualizaci)
ME_MEV = 0.511

# Definice škál (Tvé rovnice)
def get_lepton_mass(k): return k * (4 * PI * N**3) * ME_MEV
def get_meson_mass(k):  return k * ALPHA_INV * ME_MEV
def get_baryon_mass(k): return k * (PI**5) * ME_MEV

# --- 2. GENERATOR DAT ---
def generate_lattice(max_k=150):
    particles = []

    # Procházíme uzly k od 1 do max_k
    for k in range(1, max_k + 1):
        # Lepton Scale (Blue/Cyan)
        m_lep = get_lepton_mass(k)
        particles.append({"mass": m_lep, "type": "Lepton", "k": k, "size": 10})

        # Meson Scale (Green)
        m_mes = get_meson_mass(k)
        particles.append({"mass": m_mes, "type": "Meson", "k": k, "size": 15})

        # Baryon Scale (Red/Gold)
        m_bar = get_baryon_mass(k)
        # Zvýraznění Protonu (k=6)
        sz = 80 if k == 6 else 20
        particles.append({"mass": m_bar, "type": "Baryon", "k": k, "size": sz})

    return particles

# --- 3. VIZUALIZACE (RENDERER) ---
def plot_geometric_universe():
    data = generate_lattice(200)

    # Nastavení plátna (Černé pozadí pro "Vesmírný" look)
    fig = plt.figure(figsize=(12, 12), facecolor='black')
    ax = fig.add_subplot(111, projection='polar')
    ax.set_facecolor('black')

    # Odstranění mřížky a os (chceme čisté umění)
    ax.grid(False)
    ax.set_xticklabels([])
    ax.set_yticklabels([])
    ax.spines['polar'].set_visible(False)

    print("Generuji fraktální vesmír...")

    # Vykreslení částic
    for p in data:
        # LOGIKA SOUŘADNIC (Magie vizualizace)
        # Radius = Logaritmus hmotnosti (aby se tam vešel mion i top kvark)
        r = np.log(p["mass"])

        # Úhel = Hmotnost * Alpha (To vytvoří spirálovou interferenci)
        # Pokud je hmota kvantována podle Alpha, vytvoří to "ramena"
        theta = p["mass"] * ALPHA * 0.1

        # Barvy podle škály
        color = 'white'
        alpha = 0.6
        if p["type"] == "Lepton":
            color = '#00ffff' # Cyan
            alpha = 0.4
        elif p["type"] == "Meson":
            color = '#00ff00' # Matrix Green
            alpha = 0.3
        elif p["type"] == "Baryon":
            color = '#ffaa00' # Gold
            alpha = 0.5

        # Zvýraznění známých částic (Tvé trefy)
        # Mion (Lepton k=1)
        if p["type"] == "Lepton" and p["k"] == 1:
            ax.scatter(theta, r, s=300, c='white', edgecolors='cyan', zorder=10, marker='*')
            ax.text(theta, r+0.2, "Muon", color='cyan', fontsize=10, ha='center')
            continue

        # Proton (Baryon k=6)
        if p["type"] == "Baryon" and p["k"] == 6:
            ax.scatter(theta, r, s=500, c='red', edgecolors='yellow', zorder=10, marker='o')
            ax.text(theta, r+0.2, "PROTON\n(Foundation)", color='yellow', fontsize=12, ha='center', fontweight='bold')
            continue

        # Tau (Lepton k=17)
        if p["type"] == "Lepton" and p["k"] == 17:
            ax.scatter(theta, r, s=200, c='white', edgecolors='cyan', zorder=10)
            ax.text(theta, r+0.2, "Tau", color='cyan', fontsize=9)
            continue

        # Vykreslení běžného uzlu
        ax.scatter(theta, r, s=p["size"], c=color, alpha=alpha, edgecolors='none')

    # 4. PŘIDÁNÍ "ALPHA WALL" (Hranice vesmíru)
    # Kde končí stabilita (kolem 200 GeV)
    r_wall = np.log(200000)
    ax.plot(np.linspace(0, 2*PI, 100), [r_wall]*100, color='red', linestyle='--', linewidth=1, alpha=0.5)
    ax.text(0, r_wall + 0.1, "THE ALPHA WALL (Limit of Stability)", color='red', ha='center', fontsize=10)

    # Titulek
    plt.title("THE GEOMETRIC UNIVERSE\n(Procedural Generation form constants $\pi, \\alpha, N$)",
              color='white', fontsize=15, pad=20)

    # Podpis
    plt.figtext(0.5, 0.02, "Generated by Python | Model: Jan Šági", ha="center", color="gray", fontsize=8)

    plt.show()

if __name__ == "__main__":
    plot_geometric_universe()